### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DoaiNguyen** [googleanalytics/hello-world-android-app#6]
Fatal Exception: java.lang.RuntimeException: Unable to start service com.google.android.gms.analytics.AnalyticsService@4111f370 with null: java.lang.NullPointerException
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2859)
       at android.app.ActivityThread.access$1900(ActivityThread.java:162)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5371)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.google.android.gms.analytics.AnalyticsService.int onStartCommand(android.content.Intent,int,int)(Unknown Source)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2842)
       at android.app.ActivityThread.access$1900(ActivityThread.java:162)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5371)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by djabi** [comment]
This is a know bug that is fixed in Google Play services v9 release:
https://developers.google.com/android/guides/releases#may_2016_-_v90

Please update to that version. If the bug persist, please reopen it with Google Analytics debug logs attached.
